DATA:
  add_flips: false
  aug_permute: false
  aug_rotate: false
  aug_scale: false
  deltas: false
  segmented: false
  train_datasets:
  - jta_all_visual_cues
MODEL:
  checkpoint: ''
  dim_feedforward: 1024
  dim_hidden: 128
  eval_single: false
  grid_emb_size: 25
  grid_len: 5
  learned_embedding: true
  location_method: naive
  modality: all
  normalize_inputs: false
  num_heads: 4
  num_layers_global: 3
  num_layers_local: 6
  output_scale: 1
  residual_connection: true
  seq_len: 435
  token_num: 47
  type: transmotion
OUTPUT:
  ckpt_dir: 
  log_dir: 
  runs_dir: 
SEED: 0
TRAIN:
  aux_weight: 0.2
  batch_size: 4
  epochs: 50
  input_track_size: 9
  lr: 0.0001
  lr_decay: 1
  lr_drop: true
  max_grad_norm: 1.0
  num_workers: 0
  optimizer: adam
  output_track_size: 12
  val_frequency: 5
